name: Triage
on:
  issues:
    types: [opened]
jobs:
  commentOnNewIssues:
    name: Comment On New Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment On New Issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment 'Thank you very much for contributing! Please give us a bit of time to review it! We will be in touch soon. Please check also if you can create a Pull Request on your own. ;-)'